//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuariosGrupo
    {
        public int Id { get; set; }
        public int Grupo { get; set; }
        public int Usuario { get; set; }
    }
}
